# Generated by Django 5.1 on 2024-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='mail@example.com', max_length=254),
        ),
    ]
